package org.infosys.dummy;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;


/**
 * This is repository interface from table employee to perform crud operations and entity class is only
 for mapping the table ,service class is for business logic and controller class is for handling the request and response
 Repository interface extendas a class called JpaRepository which is provided by Spring Data JPA, it provides various methods for performing CRUD operations on the database, such as save(), findById(), findAll(), deleteById() etc.
  By extending JpaRepository, we can use these methods without having to write any implementation code, Spring Data JPA will automatically generate the implementation for us at runtime.
 */
@Repository
public interface EmployeeRepository extends JpaRepository<EmployeeEntity, Integer> {
    // We can also define custom query methods here if needed, for example:
    // List<EmployeeEntity> findByDept(String dept);
    //find by name, find by salary greater than, etc.
    //here findby,findallby, etc are keywords provided by spring data jpa to generate the query automatically based on the method name.
    //and Dept,Salary are the fields so jpa parses the methodname,fetches the field and generates the query accordingly.
    // for custom @query is also provided by spring data jpa, we can write our own query using @query annotation and specify the query in the annotation, this is useful when we want to write complex queries that cannot be generated by method name parsing.
    List<EmployeeEntity> findByDept(String dept);
    List<EmployeeEntity> findBySalaryGreaterThan(double salary);
    EmployeeEntity findByName(String name);
    @Query("SELECT e FROM EmployeeEntity e WHERE e.name LIKE %:prefix%")
    List<EmployeeEntity> findByNameStartingWith(@Param("prefix") String prefix);
    
}
